[package]
name = "3d"
version = "0.1.0"
authors = []

[dependencies]
scad_generator = {git = "https://github.com/TheZoq2/Rust-Scad.git"}
scad_util = {git = "https://github.com/TheZoq2/Rust-scad-util"}
nalgebra = "*"

